### ISSUE TITLE
When I go to the About page my computer catches fire.

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/sen#37]
## What isn’t working as expected on the website? (required)
I was expecting the About page to work. Instead it caught fire. 

## If you encountered an error message, please take a screenshot and paste it below. (required)
I did not encounter any errors. I just burned.

## What is the URL of the page where you encountered the bug? [Type NA if not applicable] (required)
http://www.grougreougergergu.org

## What browser, operating system, and device were you using when you encountered the error? (required)
OS54

## Additional context (optional)

**Comment by rcastong** [comment]
I don't want to do this right :)

**Comment by ubermichael** [comment]
have you tried rebooting?
