### ISSUE TITLE
Links to related persons on person pages broken

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/sen#49]
## What isn’t working as expected on the website? (required)

Links to a related person (i.e. someone's child) should link to another page, but they do not.

## If you encountered an error message, please take a screenshot and paste it below. (required)

N/A

## Is this the first time the error occurred? If not, describe its frequency. (required)

It happens on all person show pages 

## What is the URL of the page where you encountered the bug? [Type NA if not applicable] (required)

See person/645 and try to click on "Father: Marigny De Mandeville, Antoine Philippe"; it is a link, but it links back to person/645. 

## What steps did you take before you encountered the bug? (required)

Went to a person page via the browse

## What browser, operating system, and device were you using when you encountered the error? (required)

Chrome etc

## Additional context (optional)

**Comment by ubermichael** [comment]
Damn. It's linking to the wrong side of a relationship.
