### ISSUE TITLE
City List import

### ISSUE THREAD

**Issue by JMSpear** [sfu-dhil/sen#56]
## What isn’t working as expected on the website? (required)

Import from spreadsheet to City List.

## If you encountered an error message, please take a screenshot and paste it below. (required)

n/a

## Is this the first time the error occurred? If not, describe its frequency. (required)

n/a

## What is the URL of the page where you encountered the bug? [Type NA if not applicable] (required)

https://dhil.lib.sfu.ca/sen/city/

## What steps did you take before you encountered the bug? (required)

n/a

## What browser, operating system, and device were you using when you encountered the error? (required)

Firefox 90.0.2 (64-bit), Mac OS Majave 10.14.6

## Additional context (optional)

Import from Sacramental Records spreadsheet. Five rows had residence data. Three were entered "street address, city, state" but two only had "city, state". The first three have been correctly captured as "New Orleans, Louisiana" but the latter two seem to have been identified "New Orleans" as the street address and "Louisiana" as the city.

<img width="1193" alt="Screen Shot 2021-08-02 at 12 00 41 PM" src="https://user-images.githubusercontent.com/82979255/127910538-55b80269-e713-4baa-b611-f71db9b2c733.png">
<img width="1176" alt="Screen Shot 2021-08-02 at 12 00 51 PM" src="https://user-images.githubusercontent.com/82979255/127910540-d9d59498-be82-4252-b25b-404fd091873e.png">

**Comment by ubermichael** [comment]
Tagged this issue by mistake. Reopening.
