### ISSUE TITLE
Manumission Event Category Details date import

### ISSUE THREAD

**Issue by JMSpear** [sfu-dhil/sen#68]
## What isn’t working as expected on the website? (required)

In the Event List page (https://dhil.lib.sfu.ca/sen/event/?page=1), the dates for the two manumission entries (Brouner at the bottom of page 1 and Beaurepos towards the top of page 2) are the only ones appearing as YYYY-MM-DD instead of being imported from the [event]_date_written column in the Sacramental Records spreadsheet. I had left the manumission_date_written columns blank in the spreadsheet but will correct that so please change the code to import from the manumission_date_written column instead of the manumission_date column for the first column of the Event List page.

<img width="1175" alt="Screen Shot 2021-08-03 at 11 39 54 AM" src="https://user-images.githubusercontent.com/82979255/128068722-fa603fa3-0449-4bfd-8ef6-c4f122b27604.png">
<img width="1181" alt="Screen Shot 2021-08-03 at 11 25 46 AM" src="https://user-images.githubusercontent.com/82979255/128068736-be2e46db-08b7-41a2-98ef-c9d62d8e007b.png">

## If you encountered an error message, please take a screenshot and paste it below. (required)

n/a

## Is this the first time the error occurred? If not, describe its frequency. (required)

n/a

## What is the URL of the page where you encountered the bug? [Type NA if not applicable] (required)

https://dhil.lib.sfu.ca/sen/event/?page=1
https://dhil.lib.sfu.ca/sen/event/?page=2

## What steps did you take before you encountered the bug? (required)

n/a

## What browser, operating system, and device were you using when you encountered the error? (required)

Firefox 90.0.2 (64-bit), Mac OS Majave 10.14.6

## Additional context (optional)

**Comment by ubermichael** [comment]
There's no change to the code needed here. If there is a written date it will be displayed. If there isn't a written date, the standardized date will be used instead.
